BugiDev/react-native-calendar-strip

src/CalendarStrip.js
If you don't pass the locale prop, an error is thrown.
Please add defaultProps or, like my pull request, check if prop is set.
=> Check if locale prop is set

README.md, src/CalendarStrip.js
useIsoWeekday controls whether the start of the week is on the ISO week day (default, same as previous behavior) or the passed in startingDate day.
=> Add useIsoWeekday option to start week on ISO or given week day

src/CalendarDay.js
Touch detection is now on the date container instead of just its text.  This is accomplished by swapping the TouchableOpacity and Animated.View containers.
=> Fix date touch selection consistency.

src/CalendarStrip.js
The startingDate does not set itself correctly if no prop is passed in.   This causes issues showing the correct week when the selectedDate prop is used.  
You currently have to specify the startingDate prop when using the selectedDate prop.  This removes that requirement.
I suspect that this is the problem with issue https://github.com/BugiDev/react-native-calendar-strip/issues/27 amongst other things.
=> Fix startingDate bugs

src/CalendarHeader.js, src/CalendarStrip.js
Created a new CalendarHeader Component in an attempt to simplify the code a little bit.  This new component only uses props and no state. 
I've also added a shouldComponentUpdate function to the CalendarHeader to prevent the recalculation of the header when it isn't required.  I just used JSON.stringify for comparison here as I wasn't sure whether to add external libraries to do this (eg lodash or deep-equal or whatever).
=> Extracted CalendarHeader into its own component

.gitignore, __tests__/WeekSelector.js, __tests__/__snapshots__/WeekSelector.js.snap, src/CalendarStrip.js, src/WeekSelector.js
This extracts a new WeekSelector component from the main CalendarStrip Component.  The new component uses no state and works with the passed in props.  
Tests are included and bug fix applied where the opacity wasn't being assigned if a custom leftSelector or rightSelector was being used.  
More importantly, this removes some state and functionality from the CalendarStrip into the new component, especially the UpdateView function.
=> Extract WeekSelector component

src/CalendarDay.js
Fix for #22 
Using transparent background fixes problem with layout where days would overlap and circle of the selected day would get cut out.
=> Use transparent background for days that aren't selected

README.md, example/example/App.js, src/CalendarDay.js, src/CalendarHeader.js, src/CalendarStrip.js
This should solve the problem whereby the styling of the component breaks when the user sets large fonts on their phones. Specifically on iOS
=> ability to override the underlying text element allowFontScaling

src/CalendarDay.js
dateNumberFontSize was replaced by the calculated size inside CalendarDay. Now that defautl size would applied if user doesn't pass any size and if user passes size property it will be applied
issue https://github.com/BugiDev/react-native-calendar-strip/issues/86
=> Issue was: Custom Size wouldn't apply. [Fixed]

.all-contributorsrc, README.md, package.json, src/Calendar.style.js, src/CalendarDay.js, src/CalendarStrip.js
Add feature for adding marked dates.
Usage example: 
```
markedDates={{
'2018-12-03': { dots: [ { key: 1, color: 'red', selectedDotColor: 'blue' }, { key: 2, color: 'blue', selectedDotColor: 'red' } ] },
'2018-12-04': { dots: [ { key: 3, color: 'green', selectedDotColor: 'blue' }, { key: 4, color: 'blue', selectedDotColor: 'red' } ] },
'2018-12-05': { dots: [ { key: 5, color: 'white', selectedDotColor: 'blue' }, { key: 6, color: 'blue', selectedDotColor: 'red' } ] },
}}
```
=> Feature: add marked dates

README.md, index.d.ts, src/CalendarHeader.js, src/CalendarStrip.js
- Property calendarHeaderPosition added (above | below).
- Property calendarHeaderContainerStyle added.
- CalendarHeader now has Text wrapped into View for more customization flexibility.
=> More customization options for CalendarHeader

README.md
The proposed example had too much `{ }` in it
=> Fixed customDatesStyles example

index.d.ts
Created the necessary typings for useRef (https://github.com/BugiDev/react-native-calendar-strip/issues/168)
=> created typings for `useRef<CalendarStrip>()`

index.d.ts, src/CalendarStrip.js
Adding a new default prop to remove a Warning coming with a new version of react-native
All the info are in the issue #173
=> Default prop to remove warning

README.md
This pull request adds a new Device Specific Notes section to the README.md file in response to [this issue](https://github.com/BugiDev/react-native-calendar-strip/issues/86).
=> Add Device Specific Notes section in README.md

src/CalendarStrip.js
As of 2.0.4, the onWeekChanged callback is provided with both the start date for start and end parameter
=> Fixed end of week returned by onWeekChanged

src/CalendarStrip.js
Fix a rounding error inducing a bounce on ios.
=> Dates bounce when component renders #208

src/WeekSelector.js
Using Expo, running in web browser.
Warnings displayed for the original proptypes of imageSource:
index.js:1 Warning: Failed prop type: Invalid prop `imageSource` supplied to `WeekSelector`.
in WeekSelector (at CalendarStrip.js:553)
in CalendarStrip (at LogScreen.js:11)
in div (created by View)
in View (at LogScreen.js:10)
in LogScreen (created by SceneView)
in StaticContainer
in StaticContainer (created by SceneView)
in EnsureSingleNavigator (created by SceneView)
in SceneView (created by CardContainer)
in div (created by View)
in View (created by CardContainer)
in div (created by View)
in View (created by CardContainer)
in div (created by View)
in View (created by ForwardRef(CardSheet))
in ForwardRef(CardSheet) (created by Card)
in div (created by View)
in View (created by …
=> Change proptypes of imageSource in WeekSelector

index.d.ts
Correction for following the [documentation](https://github.com/ronaldaraujo/react-native-calendar-strip#day-selection-animation-options).
=> Defining properties as optional.

index.d.ts
Fix #214 issue.  
When we run `$ tsc index.d.ts` command, TypeScript no longer throws up linting errors.
=> Fix typescript linting errors

index.d.ts, src/CalendarStrip.js, src/Scroller.js
This is useful if you want to replace ScrollView with something else. 
For example you may want to sub in the ScrollView from `react-native-gesture-handler` if you are using it inside of a bottom sheet https://github.com/osdnk/react-native-reanimated-bottom-sheet.
=> Forward externalScrollView prop to RecyclerListView

index.d.ts
Missing those two props on CalendarStrip component. 
Moment is send on callback `onDateSelected` and `onWeekChanged` making errors if we do a `date.toDateString()` on the function.
=> Typescript issues

README.md, index.d.ts, src/CalendarStrip.js, src/Scroller.js
Addressing #215. `scrollerPaging` will only work if `scrollable` is also set to `true`.
=> add scrollerPaging prop

src/CalendarStrip.js
I am working on a project where whitelisted/blacklisted dates of a calendar strip are dynamic. In the current version of this component, changes to the whitelists and blacklists are not rendered until a `CalendarDay` element is clicked, which is rather confusing. This PR forces a componentwide refresh when these lists change. 
I'm not sure if it's strictly necessary to recompute `startingDate`, `selectedDate`, and `days`.
=> Changes to blacklist/whitelist should force a refresh

README.md, index.d.ts, src/CalendarDay.js, src/CalendarStrip.js
added an `upperCaseDays` prop (`true` by default) which sets the text of the day to title case when set to `false`
fixes #265
=> allow text of the days to be title case

src/Scroller.js
I got the case when `numVisibleItems` is calculated as 6 instead of 7 days and that is ruins paged scrollable. I found that before `Math.floor()` being applied the raw value is 6.94 which, I believe, is ok since it's calculated upon rounded `itemWidth` & `marginHorizontal` values. But when you floor the `numVisibleItems` itself it ends up in wrong days & unexpected paging behavior. This PR suggests to replace `Math.floor()` with `Math.round()`
I suppose it also could be a fix for issue #269
=> Fixed numVisibleItems in Scroller component

index.d.ts
[RefObject requires a type parameter](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L84)
=> Add type parameter to RefObject

src/CalendarStrip.js
This fixed is regarding to this issue https://github.com/BugiDev/react-native-calendar-strip/issues/266.
=> fixed date changed when scrolling

src/CalendarStrip.js
Fixed a bug where calling updateWeekView immediately after calling setSelectedDate would display an unintended date.
It was because setState was running asynchronously.
It is reenact with the following code.
https://snack.expo.io/E4K9r9rrQ
=> fixed shown wrong selected date when using updateWeekView immediately after call setSelectedDate.

src/CalendarStrip.js
Fix suggested here: https://github.com/BugiDev/react-native-calendar-strip/issues/303#issuecomment-864510769
=> Fixing no-op: evaluating 'datesList[_this.state.numVisibleDays - 1].date'

index.d.ts, package.json, src/CalendarDay.js
Fixed issue where the highlightDateContainerStyle was overridden by dayContainerStyle. Also added dayContainerStyle to the list of valid props for the package.
=> Highlight date container style override fix

src/CalendarDay.js
CalendarDay's `calcSizes` calculates a responsive `containerHeight` by doing `Math.round(props.height)`. Ditto for the width. 
During development, `props.height` would sometimes be `undefined`, causing it to do `Math.random(undefined)` which yielded `NaN`. This occurred even when an explicit `dayComponentHeight` was being passed in. That in turn led to the following error, causing an app crash on Android:
```
Invariant Violation: [847,"RCTView",81,{"justifyContent":"center","alignItems":"center","alignSelf":"center","width":0,"height":"<<NaN>>","borderRadius":0,"backgroundColor":0}] is not usable as a native method argument
```
- That's when using JSC and RN 0.64.2. Hermes crashes without a useful error.
- The issue was particularly prevalent when using Fast Refresh. Once it happened I …
=> Crashfix for CalendarDay having an undefined props.height
